services:
  layerinvoice:
    image: ghcr.io/basilsaeedbari/layerinvoice:latest
    container_name: layerinvoice_app
    restart: always
    volumes:
      - layerinvoice_data:/app/data
    environment:
      - DB_PATH=/app/data/layerinvoice.db
      - SESSION_SECRET=choose_a_long_secure_random_string_here_32_chars
      - APP_ENV=production
      - PORT=8080
    networks:
      - proxy-net
    labels:
      caddy: layerinvoice.basilsaeedbari.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  proxy-net:
    external: true

volumes:
  layerinvoice_data:
